// Code generated by goctl. DO NOT EDIT.
package types

type IsOK struct {
	IsOK bool `json:"IsOK"`
}

type VersionResp struct {
	AppName    string `json:"AppName"`
	AppVersion string `json:"AppVersion"`
	GoVersion  string `json:"GoVersion"`
	GitRepoUrl string `json:"GitRepoUrl"`
	GitTag     string `json:"GitTag"`
	GitHash    string `json:"GitHash"`
	BuildOS    string `json:"BuildOS"`
	BuildArch  string `json:"BuildArch"`
	TargetOS   string `json:"TargetOS"`
	TargetArch string `json:"TargetArch"`
	BuildTime  string `json:"BuildTime"`
	BuildUser  string `json:"BuildUser"`
}

type User struct {
	ID       string `json:"ID"`
	Username string `json:"Username"`
	Password string `json:"Password"`
	UpdateAt int64  `json:"UpdateAt"`
	CreateAt int64  `json:"CreateAt"`
}

type CreateUserReq struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type CreateUserResp struct {
	Code int64  `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}

type LoginReq struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type LoginRespData struct {
	ID       string `json:"ID"`
	Username string `json:"Username"`
	Token    string `json:"Token"`
	ExpireAt string `json:"ExpireAt"`
}

type LoginResp struct {
	Code int64         `json:"Code"`
	Msg  string        `json:"Msg"`
	Data LoginRespData `json:"Data"`
}

type Item struct {
	ID       string `json:"ID"`
	Name     string `json:"Name"`
	Age      int64  `json:"Age"`
	Secret   string `json:"-"`
	UpdateAt int64  `json:"UpdateAt"`
	CreateAt int64  `json:"CreateAt"`
}

type CreateItemReq struct {
	Name   string `json:"Name"`
	Age    int64  `json:"Age"`
	Secret string `json:"Secret"`
}

type CreateItemResp struct {
	Code int64  `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}

type GetItemReq struct {
	ID string `path:"id"`
}

type GetItemResp struct {
	Code int64  `json:"Code"`
	Msg  string `json:"Msg"`
	Data Item   `json:"Data"`
}

type ListItemReq struct {
	Name    string `form:"Name,optional"`
	Page    int64  `form:"Page,optional,default=1"`
	Size    int64  `form:"Size,optional,default=15"`
	OrderBy string `form:"OrderBy,optional,default=ID,options=[ID,Name,Age,UpdateAt,CreateAt]"`
	Order   string `form:"Order,optional,default=Desc,options=[Desc,Asc]"`
}

type ListItemResp struct {
	Code  int64   `json:"Code"`
	Msg   string  `json:"Msg"`
	Data  []*Item `json:"Data"`
	Total int64   `json:"Total"`
}

type UpdateItemReq struct {
	*Item
}

type UpdateItemResp struct {
	Code int64  `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}

type DeleteItemReq struct {
	ID string `path:"id"`
}

type DeleteItemResp struct {
	Code int64  `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}
