// Code generated by goctl. DO NOT EDIT.
package types

type IsOK struct {
	IsOK bool `json:"IsOK"`
}

type User struct {
	ID       string `json:"ID"`
	Username string `json:"Username"`
	Password string `json:"Password"`
	UpdateAt int64  `json:"UpdateAt"`
	CreateAt int64  `json:"CreateAt"`
}

type CreateUserReq struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type CreateUserResp struct {
	Code int    `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}

type LoginReq struct {
	Username string `json:"Username"`
	Password string `json:"Password"`
}

type LoginRespData struct {
	ID       string `json:"ID"`
	Username string `json:"Username"`
	Token    string `json:"Token"`
	ExpireAt string `json:"ExpireAt"`
}

type LoginResp struct {
	Code int           `json:"Code"`
	Msg  string        `json:"Msg"`
	Data LoginRespData `json:"Data"`
}

type Item struct {
	ID       string `json:"ID"`
	Name     string `json:"Name"`
	Age      int64  `json:"Age"`
	Secret   string `json:"-"`
	UpdateAt int64  `json:"UpdateAt"`
	CreateAt int64  `json:"CreateAt"`
}

type CreateItemReq struct {
	Name   string `json:"Name"`
	Age    int64  `json:"Age"`
	Secret string `json:"Secret"`
}

type CreateItemResp struct {
	Code int    `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}

type GetItemReq struct {
	ID string `path:"ID"`
}

type GetItemResp struct {
	Code int    `json:"Code"`
	Msg  string `json:"Msg"`
	Data Item   `json:"Data"`
}

type ListItemReq struct {
	Name    string `form:"Name,optional"`
	Page    int    `form:"Page,default=1"`
	Size    int    `form:"Size,default=15"`
	OrderBy string `form:"OrderBy,default=ID,options=[ID,Name,Age,UpdateAt,CreateAt]"`
	Order   string `form:"Order,default=Desc,options=[Desc,Asc]"`
}

type ListItemResp struct {
	Code  int    `json:"Code"`
	Msg   string `json:"Msg"`
	Data  []Item `json:"Data"`
	Total int    `json:"Total"`
}

type UpdateItemReq struct {
	ID     string `path:"ID"`
	Name   string `json:"Name"`
	Age    int64  `json:"Age"`
	Secret string `json:"Secret"`
}

type UpdateItemResp struct {
	Code int    `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}

type DeleteItemReq struct {
	ID string `path:"ID"`
}

type DeleteItemResp struct {
	Code int    `json:"Code"`
	Msg  string `json:"Msg"`
	Data IsOK   `json:"Data"`
}
