// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go_zero_example/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/item",
				Handler: CreateItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/item/:id",
				Handler: GetItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/item",
				Handler: ListItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/item/:id",
				Handler: UpdateItemHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/item/:id",
				Handler: DeleteItemHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
